import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import axios from'axios';import{LayoutDashboard,Users,Building2,Wallet,Plus,Pencil,Trash2,Search,X,TrendingUp}from'lucide-react';import'./styles.css';
const A='/api';
function App(){
 const[page,setPage]=useState('dashboard'),[employees,setEmployees]=useState([]),[dashboard,setDashboard]=useState(null),[departments,setDepartments]=useState([]),[payroll,setPayroll]=useState(null),[search,setSearch]=useState(''),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState({name:'',email:'',department:'',salary:''});
 const load=async()=>{const [e,d,dp,p]=await Promise.all([axios.get(A+'/employees'),axios.get(A+'/dashboard'),axios.get(A+'/departments'),axios.get(A+'/payroll')]);setEmployees(e.data);setDashboard(d.data);setDepartments(dp.data);setPayroll(p.data)};
 useEffect(()=>{load()},[]);
 const nav=p=>{setPage(p);setSearch('')};
 const add=()=>{setEdit(null);setForm({name:'',email:'',department:'',salary:''});setShow(true)};
 const editEmployee=e=>{setEdit(e.id);setForm({name:e.name,email:e.email,department:e.department,salary:e.salary});setShow(true)};
 const save=async ev=>{ev.preventDefault();const data={...form,salary:Number(form.salary)};edit?await axios.put(A+'/employees/'+edit,data):await axios.post(A+'/employees',data);setShow(false);await load()};
 const del=async id=>{if(confirm('Delete this employee?')){await axios.delete(A+'/employees/'+id);await load()}};
 const filtered=employees.filter(e=>(e.name+' '+e.email+' '+e.department).toLowerCase().includes(search.toLowerCase()));
 return <div className="app"><aside><div className="brand"><div className="logo">EB</div><div><b>Employee</b><span>Management</span></div></div><nav>
 {[[LayoutDashboard,'Dashboard'],[Users,'Employees'],[Building2,'Departments'],[Wallet,'Payroll']].map(([I,n])=><button className={page===n.toLowerCase()?'active':''} onClick={()=>nav(n.toLowerCase())}><I/> {n}</button>)}</nav><div className="sidefoot"><div className="avatar">AB</div><div><b>Ankit Bhange</b><small>Administrator</small></div></div></aside>
 <main><header><div><small className="eyebrow">ADMIN CONSOLE</small><h1>{page==='dashboard'?'Dashboard':page==='employees'?'Employees':page==='departments'?'Departments':'Payroll'}</h1><p>{page==='dashboard'?'Workforce overview and key metrics.':page==='employees'?'Manage employee records and information.':page==='departments'?'Department headcount and payroll distribution.':'Salary and payroll overview.'}</p></div>{page==='employees'&&<button className="primary" onClick={add}><Plus/> Add Employee</button>}</header>
 {page==='dashboard'&&dashboard&&<><div className="cards"><Card icon={<Users/>} label="Total Employees" value={dashboard.totalEmployees}/><Card icon={<Building2/>} label="Departments" value={dashboard.departments}/><Card icon={<Wallet/>} label="Monthly Payroll" value={'₹'+Number(dashboard.monthlyPayroll).toLocaleString('en-IN')}/><Card icon={<TrendingUp/>} label="Average Salary" value={'₹'+Number(dashboard.averageSalary).toLocaleString('en-IN')}/></div><section className="panel"><Head title="Recent Employees" sub={employees.length+' total records'}/><EmployeeTable data={employees.slice(-5).reverse()} editEmployee={editEmployee} del={del}/></section></>}
 {page==='employees'&&<section className="panel"><Head title="Employee Directory" sub={filtered.length+' records'} search={search} setSearch={setSearch}/><EmployeeTable data={filtered} editEmployee={editEmployee} del={del}/></section>}
 {page==='departments'&&<section className="panel"><Head title="Department Overview" sub={departments.length+' departments'}/><div className="deptgrid">{departments.map(d=><div className="dept"><div className="depticon"><Building2/></div><h3>{d.name}</h3><p>{d.employeeCount} employee{d.employeeCount!==1?'s':''}</p><strong>₹{Number(d.payroll).toLocaleString('en-IN')}</strong><small>Monthly payroll</small></div>)}</div>{!departments.length&&<div className="empty">No departments available.</div>}</section>}
 {page==='payroll'&&payroll&&<><div className="cards"><Card icon={<Wallet/>} label="Total Monthly Payroll" value={'₹'+Number(payroll.totalPayroll).toLocaleString('en-IN')}/><Card icon={<TrendingUp/>} label="Average Salary" value={'₹'+Number(payroll.averageSalary).toLocaleString('en-IN')}/></div><section className="panel"><Head title="Payroll Details" sub={employees.length+' employees'}/><table><thead><tr><th>EMPLOYEE</th><th>DEPARTMENT</th><th>SALARY</th></tr></thead><tbody>{payroll.employees.map(e=><tr><td><div className="person"><div className="mini">{e.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><b>{e.name}</b></div></td><td><span className="badge">{e.department}</span></td><td className="salary">₹{Number(e.salary).toLocaleString('en-IN')}</td></tr>)}</tbody></table></section></>}
 <footer>Created by <b>Ankit Bhange</b><span>•</span> Java • Spring Boot • React • Maven • Nexus</footer></main>
 {show&&<div className="backdrop"><div className="modal"><div className="modalhead"><div><h2>{edit?'Edit Employee':'Add Employee'}</h2><p>Enter employee information.</p></div><button className="close" onClick={()=>setShow(false)}><X/></button></div><form onSubmit={save}>{[['name','Name','text'],['email','Email','email'],['department','Department','text'],['salary','Salary','number']].map(([k,l,t])=><label>{l}<input required type={t} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={'Enter '+l.toLowerCase()}/></label>)}<div className="actions"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancel</button><button className="primary">{edit?'Update Employee':'Create Employee'}</button></div></form></div></div>}</div>
}
function Card({icon,label,value}){return <div className="card"><div className="cardicon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Head({title,sub,search,setSearch}){return <div className="panelhead"><div><h2>{title}</h2><small>{sub}</small></div>{search!==undefined&&<div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employees..."/></div>}</div>}
function EmployeeTable({data,editEmployee,del}){return <table><thead><tr><th>EMPLOYEE</th><th>EMAIL</th><th>DEPARTMENT</th><th>SALARY</th><th>ACTIONS</th></tr></thead><tbody>{data.map(e=><tr><td><div className="person"><div className="mini">{e.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{e.name}</b><small>ID #{e.id}</small></div></div></td><td>{e.email}</td><td><span className="badge">{e.department}</span></td><td className="salary">₹{Number(e.salary).toLocaleString('en-IN')}</td><td><button className="iconbtn" onClick={()=>editEmployee(e)}><Pencil/></button><button className="iconbtn danger" onClick={()=>del(e.id)}><Trash2/></button></td></tr>)}</tbody></table>}
createRoot(document.getElementById('root')).render(<App/>);
