apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-management
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: 680464296394.dkr.ecr.us-east-1.amazonaws.com/employee-management-ecr:1.0.0

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
